### PR TITLE
Init app support + standard .gitingore

### LINKED ISSUE #24: Make the package a Flask extention so it can be used with init_app
When making modular flask applications, it's common not to immediately provide the app in the constructor, but to pass it later on with the method `init_app(app)` as we can see in the documentation -- https://flask.palletsprojects.com/en/1.1.x/extensions/

With a bit of changes on the constructor this can become a "proper" flask extension 
https://flask.palletsprojects.com/en/1.1.x/extensiondev/

The example of the SQLite extension provides an idea on how this could look like:

```
    def __init__(self, app=None):
        self.app = app
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        app.config.setdefault('SQLITE3_DATABASE', ':memory:')
        app.teardown_appcontext(self.teardown)
```

### PR DESCRIPTION
**Pull request by sergioisidoro**
Fixes #24 

Adds support for `init_app` flask extension style - More details in #24

### CODE REVIEW

**Comment by twelvelabs** [comment]
@alexchamberlain (or anyone at @bloomberg-oss): is there any chance of this getting merged sometime soon? I'm interested in using this library on a project that uses the flask factory pattern and this would be super helpful. Thanks!

**Comment by alexchamberlain** [comment]
Apologies for the slow response here - I have updated my notification settings, so that I get notifications from the `bloomberg` org to my bloomberg address, so hopefully, I'll be more responsive.

On the code itself, I think it looks great - thanks for taking the time to make the change. I've posted 1 additional commit that uses a `property` instead of a setter. @sergioisidoro Is that OK with you?

On `.gitignore`s, I'll be honest - I'm not a massive fan. I encourage people to use [a global .gitignore](https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer), especially for editor-specific files. What do you think?

**Comment by alexchamberlain** [comment]
See also https://github.com/bloomberg/python-github-webhook/pull/20 for .gitignore, limited to only those files generated by the repo.

**Comment by sergioisidoro** [comment]
Hi @alexchamberlain.

Yes, of course. Actually that was a TIL, because I've never used that `@xx.setter` pattern and it looks interesting.

On the `.gitignore` matter, I have multiple python projects in my local machine, and so the gitignore may vary from project to project (eg. some projects might have the coverage of the latest branch stored in the git). So I'm not a big fan of global gitignores.

This .gitignore is the standard provided by github (https://github.com/github/gitignore/blob/master/Python.gitignore), and I've had no issues with it. But if you feel like #20 makes more sense, go ahead :)

**Review by alexchamberlain — APPROVED** [review]

**Comment by alexchamberlain** [comment]
Released as 1.0.4

**Pull request merged**
